# Configuration for nonod
# Syntax: any command line option may be specified as 'clioptionname=value'.
#         Boolean options such as 'no-sync' are specified as 'no-sync=1'.
# See 'nonod --help' for all available options.

data-dir=/var/lib/nono
log-file=/var/log/nono/nono.log
log-level=0
